# 1. Ch?y ? c?ng 8081 ?? kh�ng ??ng h�ng v?i Project S?n Ph?m (8080)
server.port=8088
# 2. K?t n?i t?i Database ServiceStore
spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=ServiceStore;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=CafePos@123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 3. C?u h�nh Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. �p Hibernate gi? nguy�n t�n c?t (Kh�ng t? ??i th�nh d?u g?ch d??i)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# 5. Khai báo tên Service (Bắt buộc phải trùng với name trong @FeignClient của ServiceCafe)
spring.application.name=service-store
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/